export const ERROR_CODES = {
  // General errors
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  INVALID_REQUEST: "INVALID_REQUEST",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  METHOD_NOT_ALLOWED: "METHOD_NOT_ALLOWED",
  VALIDATION_ERROR: "VALIDATION_ERROR",

  // Hospital-related errors
  HOSPITAL_NOT_FOUND: "HOSPITAL_NOT_FOUND",
  HOSPITAL_ALREADY_EXISTS: "HOSPITAL_ALREADY_EXISTS",
  HOSPITAL_IMPORT_FAILED: "HOSPITAL_IMPORT_FAILED",

  // File-related errors
  FILE_NOT_FOUND: "FILE_NOT_FOUND",
  FILE_UPLOAD_FAILED: "FILE_UPLOAD_FAILED",
  FILE_DOWNLOAD_FAILED: "FILE_DOWNLOAD_FAILED",
  INVALID_FILE_FORMAT: "INVALID_FILE_FORMAT",
  FILE_TOO_LARGE: "FILE_TOO_LARGE",

  // Price-related errors
  PRICE_DATA_NOT_FOUND: "PRICE_DATA_NOT_FOUND",
  PRICE_PARSING_ERROR: "PRICE_PARSING_ERROR",
  PRICE_VALIDATION_ERROR: "PRICE_VALIDATION_ERROR",

  // Job-related errors
  JOB_NOT_FOUND: "JOB_NOT_FOUND",
  JOB_PROCESSING_FAILED: "JOB_PROCESSING_FAILED",
  JOB_ALREADY_RUNNING: "JOB_ALREADY_RUNNING",
  QUEUE_UNAVAILABLE: "QUEUE_UNAVAILABLE",

  // External API errors
  EXTERNAL_SERVICE_ERROR: "EXTERNAL_SERVICE_ERROR",
  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
  INVALID_API_RESPONSE: "INVALID_API_RESPONSE",

  // Database errors
  DATABASE_CONNECTION_ERROR: "DATABASE_CONNECTION_ERROR",
  DATABASE_QUERY_ERROR: "DATABASE_QUERY_ERROR",
  DATABASE_CONSTRAINT_ERROR: "DATABASE_CONSTRAINT_ERROR",

  // Configuration errors
  CONFIGURATION_ERROR: "CONFIGURATION_ERROR",
  MISSING_ENVIRONMENT_VARIABLE: "MISSING_ENVIRONMENT_VARIABLE",

  // Analytics errors
  ANALYTICS_CALCULATION_ERROR: "ANALYTICS_CALCULATION_ERROR",
  ANALYTICS_DATA_UNAVAILABLE: "ANALYTICS_DATA_UNAVAILABLE",

  // Storage errors
  STORAGE_CONNECTION_ERROR: "STORAGE_CONNECTION_ERROR",
  STORAGE_OPERATION_FAILED: "STORAGE_OPERATION_FAILED",
  STORAGE_QUOTA_EXCEEDED: "STORAGE_QUOTA_EXCEEDED",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
